# hash-identificacao: 0cb26bd0ae3ef9790b07886f3d9562a5b89c1cb5f778708932ca0117ae5b3a77

# Configurações padrão disponíveis: https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring.application.name=projeto

# --- Servidor Web ---
# server.port=8080
# server.servlet.context-path=/  # Opcional: definir um contexto base para a API

# --- Jackson (serialização JSON formatada) ---
spring.jackson.serialization.INDENT_OUTPUT=true