# hash-identificacao: 0cb26bd0ae3ef9790b07886f3d9562a5b89c1cb5f778708932ca0117ae5b3a77

# Configurações padrão disponíveis: https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring.application.name=projeto

# --- Servidor Web ---
# server.port=8080
# server.servlet.context-path=/  # Opcional: definir um contexto base para a API

# --- Console Web do H2 (disponível em http://localhost:8080/h2-console) ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- Banco de Dados H2 (arquivo em disco) ---
spring.datasource.url=jdbc:h2:file:./data/dadospessoais;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- Inicialização de scripts SQL ---
spring.sql.init.mode=always
spring.sql.init.platform=h2
spring.sql.init.encoding=UTF-8

# --- Jackson (serialização JSON formatada) ---
spring.jackson.serialization.INDENT_OUTPUT=true