CREATE TABLE IF NOT EXISTS PROFESSORES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  matricula VARCHAR(20) NOT NULL,
  disciplina VARCHAR(50) NOT NULL,
  ativo BOOLEAN NOT NULL
);
